name: Run test backend

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.8"
          enable-cache: true
      - run: docker compose down -v --remove-orphans
      - run: docker compose up -d db
      - name: Migrate DB
        run: uv run bash scripts/prestart.sh
        working-directory: backend
      - name: Run tests
        run: PYTHONPATH=$(pwd) uv run pytest
        working-directory: backend
        env:
            PYTHONPATH: $(pwd)
      - run: docker compose down -v --remove-orphans
